CREATE TABLE ENGINEER(
  ID VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  NAME VARCHAR(16) NOT NULL,
  EMAIL VARCHAR(32) NOT NULL,
  `KEY` VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO ENGINEER VALUES(
'test',
'test',
'tester',
'test@tester.com',
'SERW12134SE'
);